### ISSUE TITLE
subprocess.CalledProcessError: Command 'sga index Contigs.fa' returned non-zero exit status 1

### ISSUE THREAD

**Issue by nityendra21** [chjiao/PEHaplo#16]
Hi, I'm experiencing the following error when trying to assemble the paired-end reads:

```
Size of File:0
Number of Strings: K 0
Size of strings:0
Creating tree: 
User Time for Constructing tree with no sorting required: 0 ms
Segmentation fault (core dumped)
The nodes of the whole graph is: 0; the edges of the whole graph is: 0.
index: input file is empty
Traceback (most recent call last):
  File "../pehaplo.py", line 157, in <module>
    main()
  File "../pehaplo.py", line 102, in main
    subprocess.check_call('sga index Contigs.fa', shell=True)
  File "/home/thermite/anaconda3/envs/tarvir/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sga index Contigs.fa' returned non-zero exit status 1
```

I'm running Python 2.7 and followed the steps as stated in the Readme as well as my paired end reads are in the 'reads1/1' format. 
Thanks!

**Comment by carolinasisco** [comment]
Hi, I got the same error, could you fix it?

**Comment by chjiao** [comment]
Hi, looks like the `sga` command get an empty input file (`Contigs.fa`), you can check if you have the middle file `kept_num.fa`, if this file is not empty, probably reduce your overlap threshold.

The issue here is that `Configs.fa` file is empty. The general way to debug the code is to check the middle results at different steps in PEHaplo main script: https://github.com/chjiao/PEHaplo/blob/eeb564329ed7f5b5b99d1b79a81d7962fc13eeca/pehaplo.py#L71

**Comment by nityendra21** [comment]
Reducing the overlap threshold worked for me. Thanks!
